name: To Do CI of node app
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Build image
        run: docker build .  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 528267078178.dkr.ecr.ap-south-1.amazonaws.com
          docker build -t ecr-repo .
          docker tag ecr-repo:latest 528267078178.dkr.ecr.ap-south-1.amazonaws.com/ecr-repo:latest
          docker push 528267078178.dkr.ecr.ap-south-1.amazonaws.com/ecr-repo:latest